packages:
  - "benchmarks/*"

allowBuilds:
  es5-ext: false
  esbuild: false

minimumReleaseAgeExclude:
  - "@orpc/client@2.0.0-beta.35"
  - "@orpc/contract@2.0.0-beta.35"
  - "@orpc/json-schema@2.0.0-beta.35"
  - "@orpc/openapi@2.0.0-beta.35"
  - "@orpc/server@2.0.0-beta.35"
  - "@orpc/shared@2.0.0-beta.35"
  - "@standard-server/aws-lambda@0.9.0"
  - "@standard-server/core@0.9.0"
  - "@standard-server/fastify@0.9.0"
  - "@standard-server/fetch@0.9.0"
  - "@standard-server/node@0.9.0"
  - "@standard-server/peer@0.9.0"
  - "@standard-server/shared@0.9.0"

shamefullyHoist: true
